### PR TITLE
1.12 compatibility

### LINKED ISSUE #898: shipyard 1.12 branch problem
`git clone https://github.com/shipyard/shipyard.git && cd shipyard`
`git checkout 1.12`
`docker-compose build`
`docker-compose up`

Hi, I am having problems with this step. details as follows:
1. docker-compose up 
2. log in http://192.168.56.102:8080

3. go to the "Get Started" page
4. Click the “Initialize” button

but ,No response after clicking. 
the ssh console logs:
controller_1 | time="2016-11-10T02:50:06Z" level=debug msg="POST: /swarm/init"

On the “Initialize” page , open chrome F12 console and Refresh, Output 406 error:
GET http://192.168.56.102:8080/swarm 406 (Not Acceptable)

Click the “Initialize” button, Output 500 error:
POST http://192.168.56.102:8080/swarm/init 500 (Internal Server Error)

docker compose version:  
`docker-compose version 1.8.1, build 878cff1`
`docker-py version: 1.10.3`
`CPython version: 2.7.5`
`OpenSSL version: OpenSSL 1.0.1e-fips 11 Feb 2013`

How to solve this problem? thanks.

### PR DESCRIPTION
**Pull request by tombee**
This switches our UI to use `create-react-app` for managing our build.

It also updates the UI to be compatible with 1.12.

Fixes #898

/cc @ehazlett

### CODE REVIEW

File: ui/src/actions/swarm.js [hunk 1]
```diff
@@ -1,8 +1,10 @@
-export function updateSwarmSettings(spec, version) {
+export function updateSwarmSettings(spec, version, rotateManagerToken, rotateWorkerToken) {
```
Comment (tombee) [inline ui/src/actions/swarm.js:1]: Switched our settings page to use join tokens instead of the passphrases that were removed before the 1.12 release.

File: Makefile [hunk 2]
```diff
@@ -18,7 +22,8 @@ remote-build:
 	@cd controller && docker run --rm -w /go/src/github.com/shipyard/shipyard --entrypoint /bin/bash shipyard-build -c "make build 1>&2 && cd controller && tar -czf - controller" | tar zxf -
 
 media:
-	@cd controller/static && npm install && npm run build
+	docker build -t $(UI_BUILD_IMAGE) -f ui/Dockerfile.build ui && \
```
Comment (tombee) [inline Makefile:25]: Media builds are done in a container now and produce a tarball for the built UI bits.

File: Dockerfile.build [hunk 3]
```diff
@@ -1,15 +1,14 @@
 FROM golang:1.5
 
-RUN curl -sL https://deb.nodesource.com/setup_6.x | bash -
```
Comment (tombee) [inline Dockerfile.build:3]: Since the UI builds in its own build container, we can drop this node stuff from our build image.

File: controller/Dockerfile [hunk 4]
```diff
@@ -1,7 +1,7 @@
 FROM alpine:latest
 RUN apk add --update git ca-certificates && \
     rm -rf /var/cache/apk/*
-ADD static /static
+ADD static.tar.gz .
```
Comment (tombee) [inline controller/Dockerfile:4]: Our final image just adds the built tarball now.

**Comment by ehazlett** [comment]
LGTM
